swagger: "2.0"
info:
  title: Satellite Image Loader
  description: Service to interact with satellite images on a database
  version: "1.0"
host: localhost:80
basePath: /image-loader/api/v1
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /processed-images:
    get:
      tags:
      - Processed images
      summary: Get processed satellite image Processed images
      description: get a processed image from the database
      operationId: Processed images#Get processed satellite image
      parameters:
      - name: Get Processed Satellite ImageRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/ProcessedImagesGetProcessedSatelliteImageRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ProcessedImagesGetProcessedSatelliteImageResponseBody'
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/ProcessedImagesGetProcessedSatelliteImageBadRequestResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ProcessedImagesGetProcessedSatelliteImageInternalErrorResponseBody'
      schemes:
      - http
    post:
      tags:
      - Processed images
      summary: Load new processed satellite image Processed images
      description: loads a new processed image into the database
      operationId: Processed images#Load new processed satellite image
      parameters:
      - name: Load New Processed Satellite ImageRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/ProcessedImagesLoadNewProcessedSatelliteImageRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ProcessedImagesLoadNewProcessedSatelliteImageResponseBody'
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/ProcessedImagesLoadNewProcessedSatelliteImageBadRequestResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ProcessedImagesLoadNewProcessedSatelliteImageInternalErrorResponseBody'
      schemes:
      - http
  /raw-images:
    get:
      tags:
      - Raw images
      summary: Get raw satellite image Raw images
      description: get a raw image from the database
      operationId: Raw images#Get raw satellite image
      parameters:
      - name: Get Raw Satellite ImageRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/RawImagesGetRawSatelliteImageRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/RawImagesGetRawSatelliteImageResponseBody'
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/RawImagesGetRawSatelliteImageBadRequestResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/RawImagesGetRawSatelliteImageInternalErrorResponseBody'
      schemes:
      - http
    post:
      tags:
      - Raw images
      summary: Load new raw satellite image Raw images
      description: loads a new image into the database
      operationId: Raw images#Load new raw satellite image
      parameters:
      - name: Load New Raw Satellite ImageRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/RawImagesLoadNewRawSatelliteImageRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/RawImagesLoadNewRawSatelliteImageResponseBody'
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/RawImagesLoadNewRawSatelliteImageBadRequestResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/RawImagesLoadNewRawSatelliteImageInternalErrorResponseBody'
      schemes:
      - http
definitions:
  GeographicInformationRequestBody:
    title: GeographicInformationRequestBody
    type: object
    properties:
      coordinates:
        type: object
        description: Coordinates of the satellite image
        example:
          Corporis autem omnis amet nemo ut.: 0.8799015965306857
          Eos qui mollitia explicabo est corporis officia.: 0.5350298753548278
          Est harum.: 0.4641900032676375
        additionalProperties: true
      tag_name:
        type: string
        description: Non-forgetable identifier
        example: Consectetur numquam et.
    example:
      coordinates:
        Alias modi molestiae dolorem quas numquam.: 0.0298195161420244
        Facere qui dolores quia iusto sint.: 0.006707504438042929
        Odit suscipit mollitia.: 0.01823829152404492
      tag_name: Omnis omnis quasi necessitatibus.
  NormalizedIndexesRequestBody:
    title: NormalizedIndexesRequestBody
    type: object
    properties:
      ndvi:
        type: array
        items:
          type: number
          example: 0.24579687160203864
          format: double
        description: Normalized difference vegetation index
        example:
        - 0.8639196191267979
        - 0.62920999890917
        - 0.8163837062280556
      ndwi:
        type: array
        items:
          type: number
          example: 0.4820876163670806
          format: double
        description: Normalized difference water index
        example:
        - 0.6377983805667723
        - 0.3906738630499499
        - 0.1828987573968838
        - 0.0401356398891894
    example:
      ndvi:
      - 0.9699480294321668
      - 0.012781916079448325
      - 0.9404237273206197
      - 0.7162157000100869
      ndwi:
      - 0.9092582679146045
      - 0.3989343481767013
      - 0.6383522880150814
      - 0.5228368161155966
  ProcessedImagesGetProcessedSatelliteImageBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Get processed satellite image_BadRequest_Response_Body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ProcessedImagesGetProcessedSatelliteImageInternalErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Get processed satellite image_InternalError_Response_Body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ProcessedImagesGetProcessedSatelliteImageRequestBody:
    title: ProcessedImagesGetProcessedSatelliteImageRequestBody
    type: object
    properties:
      file_name:
        type: string
        description: File name of the processed image
        example: Modi aut.
    example:
      file_name: Voluptas culpa dolores debitis facilis saepe blanditiis.
  ProcessedImagesGetProcessedSatelliteImageResponseBody:
    title: 'Mediatype identifier: vnd.application/goa.result+json; view=default'
    type: object
    properties:
      code:
        type: string
        description: The operation code
        example: Sint facilis eius omnis alias fuga.
      description:
        type: string
        description: The operation description
        example: Quidem sint dolores neque ut corrupti.
    description: Get Processed Satellite ImageResponseBody result type (default view)
    example:
      code: Voluptatum ex atque consequatur possimus sit consequuntur.
      description: Voluptatem et ut quas.
  ProcessedImagesLoadNewProcessedSatelliteImageBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Load new processed satellite image_BadRequest_Response_Body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ProcessedImagesLoadNewProcessedSatelliteImageInternalErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Load new processed satellite image_InternalError_Response_Body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ProcessedImagesLoadNewProcessedSatelliteImageRequestBody:
    title: ProcessedImagesLoadNewProcessedSatelliteImageRequestBody
    type: object
    properties:
      date_time:
        type: string
        description: When was the image taken
        example: "1993-12-27T08:53:05Z"
        format: date-time
      file_name:
        type: string
        description: File name of the processed image
        example: Error occaecati qui voluptatem voluptas.
      geographic_information:
        $ref: '#/definitions/GeographicInformationRequestBody'
      normalized_indexes:
        $ref: '#/definitions/NormalizedIndexesRequestBody'
    example:
      date_time: "1984-04-22T18:23:34Z"
      file_name: Officiis perferendis earum.
      geographic_information:
        coordinates:
          Dolores aut reprehenderit tempore nesciunt.: 0.08537234062709087
          Incidunt odit tempore.: 0.4612094935047014
        tag_name: Ut qui.
      normalized_indexes:
        ndvi:
        - 0.3904972148805288
        - 0.6699739812364446
        - 0.027588443100172985
        ndwi:
        - 0.508680136375543
        - 0.9307709997993568
  ProcessedImagesLoadNewProcessedSatelliteImageResponseBody:
    title: 'Mediatype identifier: vnd.application/goa.result+json; view=default'
    type: object
    properties:
      code:
        type: string
        description: The operation code
        example: Unde iure.
      description:
        type: string
        description: The operation description
        example: At doloremque voluptatem repellat et.
    description: Load New Processed Satellite ImageResponseBody result type (default view)
    example:
      code: Dolorem laborum illum facere autem.
      description: Corrupti eligendi animi id tempora voluptatem recusandae.
  RawImagesGetRawSatelliteImageBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Get raw satellite image_BadRequest_Response_Body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  RawImagesGetRawSatelliteImageInternalErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Get raw satellite image_InternalError_Response_Body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  RawImagesGetRawSatelliteImageRequestBody:
    title: RawImagesGetRawSatelliteImageRequestBody
    type: object
    properties:
      file_name:
        type: string
        description: File name of the raw image
        example: Dignissimos accusamus aut.
    example:
      file_name: Consectetur neque voluptas laudantium facere qui.
  RawImagesGetRawSatelliteImageResponseBody:
    title: 'Mediatype identifier: vnd.application/goa.result+json; view=default'
    type: object
    properties:
      code:
        type: string
        description: The operation code
        example: Maxime rerum fugiat atque.
      description:
        type: string
        description: The operation description
        example: Sit eum rerum dolores ullam aliquid.
    description: Get Raw Satellite ImageResponseBody result type (default view)
    example:
      code: Laborum aliquid autem.
      description: Et sed cumque accusamus maiores.
  RawImagesLoadNewRawSatelliteImageBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Load new raw satellite image_BadRequest_Response_Body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  RawImagesLoadNewRawSatelliteImageInternalErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Load new raw satellite image_InternalError_Response_Body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  RawImagesLoadNewRawSatelliteImageRequestBody:
    title: RawImagesLoadNewRawSatelliteImageRequestBody
    type: object
    properties:
      file_name:
        type: string
        description: File name of the raw image
        example: Dicta quo explicabo ullam molestias.
      id:
        type: string
        description: The image identifier
        example: Et quod sit.
    example:
      file_name: Corporis laboriosam deserunt aliquid incidunt.
      id: Ratione voluptates libero tenetur sunt necessitatibus.
  RawImagesLoadNewRawSatelliteImageResponseBody:
    title: 'Mediatype identifier: vnd.application/goa.result+json; view=default'
    type: object
    properties:
      code:
        type: string
        description: The operation code
        example: Dolore impedit perferendis et ea.
      description:
        type: string
        description: The operation description
        example: Facere rerum similique repudiandae beatae.
    description: Load New Raw Satellite ImageResponseBody result type (default view)
    example:
      code: Deleniti at fuga.
      description: Numquam aut.
