openapi: 3.0.3
info:
  title: Satellite Image Loader
  description: Service to interact with satellite images on a database
  version: "1.0"
servers:
- url: http://localhost:80
  description: Default server for Satellite Image Loader API
paths:
  /image-loader/api/v1/processed-images:
    get:
      tags:
      - Processed images
      summary: Get processed satellite image Processed images
      description: get a processed image from the database
      operationId: Processed images#Get processed satellite image
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetRawSatelliteImageRequestBody'
            example:
              file_name: Voluptatem nihil.
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoaResult'
              example:
                code: Consectetur omnis molestiae et id.
                description: Laudantium cumque.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
    post:
      tags:
      - Processed images
      summary: Load new processed satellite image Processed images
      description: loads a new processed image into the database
      operationId: Processed images#Load new processed satellite image
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoadNewProcessedSatelliteImageRequestBody'
            example:
              date_time: "2012-04-04T19:21:12Z"
              file_name: Sunt aliquam totam dolores aut voluptatem sunt.
              geographic_information:
                coordinates:
                  Dolores aut reprehenderit tempore nesciunt.: 0.08537234062709087
                  Incidunt odit tempore.: 0.4612094935047014
                tag_name: Ut qui.
              normalized_indexes:
                ndvi:
                - 0.3904972148805288
                - 0.6699739812364446
                - 0.027588443100172985
                ndwi:
                - 0.508680136375543
                - 0.9307709997993568
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoaResult'
              example:
                code: Velit et velit et et.
                description: Sunt occaecati maiores omnis eligendi.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
  /image-loader/api/v1/raw-images:
    get:
      tags:
      - Raw images
      summary: Get raw satellite image Raw images
      description: get a raw image from the database
      operationId: Raw images#Get raw satellite image
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetRawSatelliteImageRequestBody'
            example:
              file_name: Vel omnis adipisci dolor aut nobis quia.
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoaResult'
              example:
                code: Eos ut unde sed.
                description: Cupiditate tempore odit.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
    post:
      tags:
      - Raw images
      summary: Load new raw satellite image Raw images
      description: loads a new image into the database
      operationId: Raw images#Load new raw satellite image
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoadNewRawSatelliteImageRequestBody'
            example:
              file_name: Ab fugiat voluptates architecto et.
              id: Consectetur quis sint voluptatem optio consequuntur non.
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoaResult'
              example:
                code: Ut ad.
                description: Eos occaecati eligendi sapiente.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
components:
  schemas:
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: false
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: true
      example:
        fault: true
        id: 123abc
        message: parameter 'p' must be an integer
        name: bad_request
        temporary: true
        timeout: true
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    GeographicInformation:
      type: object
      properties:
        coordinates:
          type: object
          description: Coordinates of the satellite image
          example:
            Est illum recusandae odio.: 0.19835752019624622
            Et autem et.: 0.08892882469281352
          additionalProperties: true
        tag_name:
          type: string
          description: Non-forgetable identifier
          example: Cum placeat.
      example:
        coordinates:
          Qui id.: 0.7188540978805499
          Rerum sed architecto nemo.: 0.025004774606587746
        tag_name: Nulla non id et.
    GetRawSatelliteImageRequestBody:
      type: object
      properties:
        file_name:
          type: string
          description: File name of the raw image
          example: Reprehenderit sapiente aut ratione commodi ab.
      example:
        file_name: Et ut blanditiis est ducimus omnis.
    GoaResult:
      type: object
      properties:
        code:
          type: string
          description: The operation code
          example: Voluptates voluptas mollitia minima ipsum magnam tempora.
        description:
          type: string
          description: The operation description
          example: Magnam perferendis molestias molestiae eos.
      example:
        code: Ea maxime fugiat atque fugit nulla.
        description: Perspiciatis vel quis minima.
    LoadNewProcessedSatelliteImageRequestBody:
      type: object
      properties:
        date_time:
          type: string
          description: When was the image taken
          example: "1987-05-21T20:57:38Z"
          format: date-time
        file_name:
          type: string
          description: File name of the processed image
          example: Sed aut.
        geographic_information:
          $ref: '#/components/schemas/GeographicInformation'
        normalized_indexes:
          $ref: '#/components/schemas/NormalizedIndexes'
      example:
        date_time: "1970-06-11T00:23:43Z"
        file_name: Facere delectus sit.
        geographic_information:
          coordinates:
            Dolores aut reprehenderit tempore nesciunt.: 0.08537234062709087
            Incidunt odit tempore.: 0.4612094935047014
          tag_name: Ut qui.
        normalized_indexes:
          ndvi:
          - 0.3904972148805288
          - 0.6699739812364446
          - 0.027588443100172985
          ndwi:
          - 0.508680136375543
          - 0.9307709997993568
    LoadNewRawSatelliteImageRequestBody:
      type: object
      properties:
        file_name:
          type: string
          description: File name of the raw image
          example: Sunt porro.
        id:
          type: string
          description: The image identifier
          example: Id ullam itaque rem nihil.
      example:
        file_name: Et provident totam velit.
        id: Omnis quisquam quos.
    NormalizedIndexes:
      type: object
      properties:
        ndvi:
          type: array
          items:
            type: number
            example: 0.49827176866111955
            format: double
          description: Normalized difference vegetation index
          example:
          - 0.4153704159999303
          - 0.9897261400757769
          - 0.6836162412666904
        ndwi:
          type: array
          items:
            type: number
            example: 0.6024488630297181
            format: double
          description: Normalized difference water index
          example:
          - 0.6373493752398844
          - 0.13152190185405616
      example:
        ndvi:
        - 0.904111819495114
        - 0.3269625674826508
        - 0.9908806910906924
        ndwi:
        - 0.9275947288291565
        - 0.3449628658251033
        - 0.9017560468551464
        - 0.23499740614264106
